### ISSUE TITLE
sensor_gnss_relative_s type not defined

### ISSUE THREAD

**Issue by julianoes** [PX4/PX4-GPSDrivers#105]
Since #101 there is the type `sensor_gnss_relative_s` introduced which is nowhere to be found, unless you build within PX4.

@dagar.

**Comment by dagar** [comment]
I don't think it's any different than `sensor_gps_position_s` and `satellite_info_s` where you have to provide it. I personally don't like that structure.

**Comment by bkueng** [comment]
It's a trade-off to use the uorb struct directly.

**Comment by bkueng** [comment]
We can add it and allow it to be overridden via macro.

**Comment by julianoes** [comment]
Right, I realized that it's the way this API works, nevermind. I'll copy it in for now. Thanks!

**Comment by mnumanuyar** [comment]
I have proposed a merge request for readme.md that notify users about the required definitions. It is probably not complete, (and maybe not upto standarts as I am not a native speaker) so please take a look

**Comment by oliviermbida** [comment]
If you get this error when building QgroundControl v4.2 then you need to :
git checkout  6fcf068949

The error appears if you manually clone this repo PX4-GPSDrivers into the submodule in the GPS directory of QgroundControl repo.
In my case I got the error  "sensor_gnss_relative_s type not defined" 
and after I checkout  6fcf068949 which is the specific commit for GPS drivers build with QgroundControl v4.2 the error when away.
