### ISSUE TITLE
GNSS accuracy loss for Trimble MB-two caused by wrong Type casting

### ISSUE THREAD

**Issue by qst0528** [PX4/PX4-GPSDrivers#117]
Reproduced on: [PX4-Autopilot 1.13.0 beta2](https://github.com/PX4/PX4-Autopilot/releases/tag/v1.13.0-beta2
)
Symptom: lat and lon has only zeros after decimal point

Our Pixhawk6C with v1.13.0 beta2 cannot parse GNSS message from Trimble MB-two.
Accessing Trimble module via its built-in web server returns far accurate position.

We assume wrong type cast in 038a13f7c2f3e2d28ac8cb6c018911902abe1a49 causing this problem.
I'm trying to build a firmware with fixed code, which I haven't succeeded yet.

Old:
`_gps_position->lat = static_cast<int>((int(lat * 0.01) + (lat * 0.01 - int(lat * 0.01)) * 100.0 / 60.0) * 10000000);`
New:
`_gps_position->lat = static_cast<int>((static_cast<int>(lat * 0.01) + static_cast<int>(lat * 0.01 - int(lat * 0.01)) * 100.0 / 60.0) * 10000000);`
Suggestion:
`_gps_position->lat = static_cast<int>((static_cast<int>(lat * 0.01) + (lat * 0.01 - static_cast<int>(lat * 0.01)) * 100.0 / 60.0) * 10000000);`

![mb-two_accuracy_loss](https://user-images.githubusercontent.com/10579105/202955358-267ec8c3-7318-4f5c-9376-996e5b83e50b.png)
![IMG_7949](https://user-images.githubusercontent.com/10579105/202955355-608cdd46-00c5-4426-83ed-72860f8f8124.jpg)

**Comment by takurx** [comment]
src/ashtech.cpp, line 420-421
https://github.com/PX4/PX4-GPSDrivers/commit/038a13f7c2f3e2d28ac8cb6c018911902abe1a49

**Comment by bkueng** [comment]
Indeed this change was incorrect and I overlooked the 2. part. Can you create a PR with your suggestion?

**Comment by qst0528** [comment]
PR merged.  Closing.
