### ISSUE TITLE
M9N UART Broken on Latest Commit

### ISSUE THREAD

**Issue by AlexKlimaj** [PX4/PX4-GPSDrivers#82]
I'm working on testing my M9N based CAN GPS. I rebased against master today and discovered that my GPS was no longer working. gps status showed not okay and it was not communicating. Reverting commit f3c4c97bc87712b84b89cc54f12f51d31ac0038d fixes the issue. @Igor-Misic @bkueng

**Comment by Igor-Misic** [comment]
**UART** is broken while workin on **CAN** GPS, and is working again when **I2C** messages are not enabled. I got lost a bit.  :)

**Comment by AlexKlimaj** [comment]
Yeah sorry it is a bit confusing. My board is using an STM32F412 as a PX4 Cannode. I have a U-blox M9N GPS connected to UART0. I'm not sure if this is specific to the M9N. I'll have to test with a Pixhawk 4 GPS that has an M8N.

**Comment by AlexKlimaj** [comment]
Just verified with a standalone M9N and a Pixhawk 4 that it is not working there as well.
I also confirmed that the M8N works with f3c4c97bc87712b84b89cc54f12f51d31ac0038d. So this is isolated to the M9N.

Master with f3c4c97bc87712b84b89cc54f12f51d31ac0038d reverted.
```
nsh> gps status
INFO  [gps] Main GPS
INFO  [gps] protocol: UBX
INFO  [gps] status: OK, port: /dev/ttyS0, baudrate: 115200
INFO  [gps] sat info: disabled
INFO  [gps] rate reading:                  949 B/s
INFO  [gps] rate position:                7.41 Hz
INFO  [gps] rate velocity:                7.41 Hz
INFO  [gps] rate publication:             6.84 Hz
INFO  [gps] rate RTCM injection:          0.00 Hz
 sensor_gps_s
        timestamp: 17226032  (0.117222 seconds ago)
        time_utc_usec: 0
        device_id: 11075589 (Type: 0xA9, SERIAL:0 (0x00))
        lat: 0
        lon: 0
        alt: -17000
        alt_ellipsoid: 0
        s_variance_m_s: 22.5000
        c_variance_rad: 3.1416
        eph: 4294967.5000
        epv: 3750000.2500
        hdop: 99.9900
        vdop: 99.9900
        noise_per_ms: 74
        jamming_indicator: 88
        vel_m_s: 0.0000
        vel_n_m_s: 0.0000
        vel_e_m_s: 0.0000
        vel_d_m_s: 0.0000
        cog_rad: 0.0000
        timestamp_time_relative: 0
        heading: nan
        heading_offset: 0.0000
        automatic_gain_control: 0
        fix_type: 0
        jamming_state: 0
        vel_ned_valid: False
        satellites_used: 0
nsh>
```
Master with f3c4c97bc87712b84b89cc54f12f51d31ac0038d included.
```
nsh> gps status
INFO  [gps] Main GPS
INFO  [gps] protocol: UBX
INFO  [gps] status: NOT OK, port: /dev/ttyS0, baudrate: 0
INFO  [gps] sat info: disabled
INFO  [gps] rate reading:                    0 B/s
nsh>
```

**Comment by Igor-Misic** [comment]
Can you try to comment on this line to see if this will help?
https://github.com/PX4/PX4-GPSDrivers/commit/f3c4c97bc87712b84b89cc54f12f51d31ac0038d#diff-1febc78d26e00434cf70e92631383f784fdb02aa7170afd41fb6eff90114d0b8R647

This is the only one that looks suspicious. F9N doesn't have **CFG-I2COUTPROT-RTCM3X**  message. 

![image](https://user-images.githubusercontent.com/10188706/118353461-94a40180-b566-11eb-884d-e888cef9d50b.png)

**Comment by AlexKlimaj** [comment]
@Igor-Misic Looks like that fixed it.

**Comment by Igor-Misic** [comment]
Solved: https://github.com/PX4/PX4-GPSDrivers/pull/83
