### ISSUE TITLE
Submodule not working

### ISSUE THREAD

**Issue by REGATTE** [PX4/PX4-GPSDrivers#95]
```
../src/GPS/Drivers/src/ubx.cpp:1981: error: no member named 'heading_accuracy' in 'sensor_gps_s'
```

Hi,
I've been developing QGC as a hobbyist, and the first I try to compile to QGC, I get this error. Anyway to sort it out??

**Comment by bkueng** [comment]
You need to make sure the submodule points to the right commit -> `git submodule update`

**Comment by REGATTE** [comment]
oh okay, thanks.
It worked when i pointed it to an older commit.
